
#ifndef FSAGABITMAPS_HEADER
#define FSAGABITMAPS_HEADER

#include "fsagaconstants.h"
#include "../allegroincludes.h"


ALLEGRO_BITMAP *floor1;
ALLEGRO_BITMAP *floor2;
ALLEGRO_BITMAP *sprite1;
ALLEGRO_BITMAP *pill1;
ALLEGRO_BITMAP *pill2;

ALLEGRO_BITMAP *serf1;
ALLEGRO_BITMAP *serf2;
ALLEGRO_BITMAP *serf3;
ALLEGRO_BITMAP *serf4;
ALLEGRO_BITMAP *serf5;
ALLEGRO_BITMAP *serf6;
ALLEGRO_BITMAP *serf7;
ALLEGRO_BITMAP *serf8;

ALLEGRO_BITMAP *serb1;
ALLEGRO_BITMAP *serb2;
ALLEGRO_BITMAP *serb3;
ALLEGRO_BITMAP *serb4;
ALLEGRO_BITMAP *serb5;
ALLEGRO_BITMAP *serb6;
ALLEGRO_BITMAP *serb7;
ALLEGRO_BITMAP *serb8;

ALLEGRO_BITMAP *serr1;
ALLEGRO_BITMAP *serr2;
ALLEGRO_BITMAP *serr3;
ALLEGRO_BITMAP *serr4;
ALLEGRO_BITMAP *serr5;
ALLEGRO_BITMAP *serr6;
ALLEGRO_BITMAP *serr7;
ALLEGRO_BITMAP *serr8;

ALLEGRO_BITMAP *serl1;
ALLEGRO_BITMAP *serl2;
ALLEGRO_BITMAP *serl3;
ALLEGRO_BITMAP *serl4;
ALLEGRO_BITMAP *serl5;
ALLEGRO_BITMAP *serl6;
ALLEGRO_BITMAP *serl7;
ALLEGRO_BITMAP *serl8;


//Seren Diagonals

//down left
ALLEGRO_BITMAP *serdl1;
ALLEGRO_BITMAP *serdl2;
ALLEGRO_BITMAP *serdl3;
ALLEGRO_BITMAP *serdl4;
ALLEGRO_BITMAP *serdl5;
ALLEGRO_BITMAP *serdl6;
ALLEGRO_BITMAP *serdl7;
ALLEGRO_BITMAP *serdl8;

//down right
ALLEGRO_BITMAP *serdr1;
ALLEGRO_BITMAP *serdr2;
ALLEGRO_BITMAP *serdr3;
ALLEGRO_BITMAP *serdr4;
ALLEGRO_BITMAP *serdr5;
ALLEGRO_BITMAP *serdr6;
ALLEGRO_BITMAP *serdr7;
ALLEGRO_BITMAP *serdr8;

//up right
ALLEGRO_BITMAP *serur1;
ALLEGRO_BITMAP *serur2;
ALLEGRO_BITMAP *serur3;
ALLEGRO_BITMAP *serur4;
ALLEGRO_BITMAP *serur5;
ALLEGRO_BITMAP *serur6;
ALLEGRO_BITMAP *serur7;
ALLEGRO_BITMAP *serur8;

//up left
ALLEGRO_BITMAP *serul1;
ALLEGRO_BITMAP *serul2;
ALLEGRO_BITMAP *serul3;
ALLEGRO_BITMAP *serul4;
ALLEGRO_BITMAP *serul5;
ALLEGRO_BITMAP *serul6;
ALLEGRO_BITMAP *serul7;
ALLEGRO_BITMAP *serul8;

//seren idle

ALLEGRO_BITMAP *seridle1;
ALLEGRO_BITMAP *seridle2;
ALLEGRO_BITMAP *seridle3;
ALLEGRO_BITMAP *seridle4;


//Seren Attacking
ALLEGRO_BITMAP *seral1;
ALLEGRO_BITMAP *seral2;
ALLEGRO_BITMAP *seral3;
ALLEGRO_BITMAP *seral4;

ALLEGRO_BITMAP *serar1;
ALLEGRO_BITMAP *serar2;
ALLEGRO_BITMAP *serar3;
ALLEGRO_BITMAP *serar4;

ALLEGRO_BITMAP *seraf1;
ALLEGRO_BITMAP *seraf2;
ALLEGRO_BITMAP *seraf3;
ALLEGRO_BITMAP *seraf4;

ALLEGRO_BITMAP *serab1;
ALLEGRO_BITMAP *serab2;
ALLEGRO_BITMAP *serab3;
ALLEGRO_BITMAP *serab4;

ALLEGRO_BITMAP *zef1;
ALLEGRO_BITMAP *zef2;
ALLEGRO_BITMAP *zef3;


ALLEGRO_BITMAP *bluf1;
ALLEGRO_BITMAP *bluf2;
ALLEGRO_BITMAP *bluf3;
ALLEGRO_BITMAP *bluf4;
ALLEGRO_BITMAP *blub1;
ALLEGRO_BITMAP *blub2;
ALLEGRO_BITMAP *blub3;
ALLEGRO_BITMAP *blub4;
ALLEGRO_BITMAP *blur1;
ALLEGRO_BITMAP *blur2;
ALLEGRO_BITMAP *blur3;
ALLEGRO_BITMAP *blur4;
ALLEGRO_BITMAP *blul1;
ALLEGRO_BITMAP *blul2;
ALLEGRO_BITMAP *blul3;
ALLEGRO_BITMAP *blul4;




ALLEGRO_BITMAP *bluf_bmps_array[MAX_SPRITE_BITMAPS];
ALLEGRO_BITMAP *ninja_bmps_array[MAX_SPRITE_BITMAPS];


ALLEGRO_BITMAP *mech;

//PALETTE the_pallete;
//COLOR_MAP trans_table;
ALLEGRO_BITMAP *wall1;
ALLEGRO_BITMAP *wall2;
ALLEGRO_BITMAP *wall3;
ALLEGRO_BITMAP *wall4;
ALLEGRO_BITMAP *chest;
ALLEGRO_BITMAP *chest2;
ALLEGRO_BITMAP *beda1;
ALLEGRO_BITMAP *door1;
ALLEGRO_BITMAP *arch1;
ALLEGRO_BITMAP *arch2;

//SPECIAL
ALLEGRO_BITMAP *t_grass;
ALLEGRO_BITMAP *t_rock;
ALLEGRO_BITMAP *t_tree;

ALLEGRO_BITMAP *textbox;
ALLEGRO_BITMAP *stairs1;
ALLEGRO_BITMAP *stairs2;
ALLEGRO_BITMAP *ninjaf1;
ALLEGRO_BITMAP *ninjaf2;
ALLEGRO_BITMAP *ninjaf3;
ALLEGRO_BITMAP *ninjaf4;
ALLEGRO_BITMAP *ninjab1;
ALLEGRO_BITMAP *ninjab2;                
ALLEGRO_BITMAP *ninjab3;
ALLEGRO_BITMAP *ninjab4;
ALLEGRO_BITMAP *ninjar1;
ALLEGRO_BITMAP *ninjar2;
ALLEGRO_BITMAP *ninjar3;
ALLEGRO_BITMAP *ninjar4;
ALLEGRO_BITMAP *ninjal1;
ALLEGRO_BITMAP *ninjal2;
ALLEGRO_BITMAP *ninjal3;
ALLEGRO_BITMAP *ninjal4;

ALLEGRO_BITMAP *top1;
ALLEGRO_BITMAP *top2;
ALLEGRO_BITMAP *shield1;
ALLEGRO_BITMAP *torch1;
ALLEGRO_BITMAP *torch2;
ALLEGRO_BITMAP *pic1;


ALLEGRO_BITMAP *batlback;
ALLEGRO_BITMAP *gold_cursor;
ALLEGRO_BITMAP *select1;
ALLEGRO_BITMAP *select2;

ALLEGRO_BITMAP *bitmap2;

ALLEGRO_BITMAP *map1;

ALLEGRO_BITMAP *colblock;
ALLEGRO_BITMAP *tagblock;
ALLEGRO_BITMAP *slash1;
ALLEGRO_BITMAP *flare1;
ALLEGRO_BITMAP *meter1;

ALLEGRO_BITMAP *convo_box;

//background
ALLEGRO_BITMAP *cloud1;
ALLEGRO_BITMAP *green1;


//top layer clouds
ALLEGRO_BITMAP *dmb_cloud;
ALLEGRO_BITMAP *fmb_cloud;
ALLEGRO_BITMAP *lcb_cloud;
ALLEGRO_BITMAP *smb_cloud;
ALLEGRO_BITMAP *smfb_cloud;
ALLEGRO_BITMAP *t_cloud;

#endif
